name: E2E on Chrome

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build_and_run_cypress_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Client Dependencies 📦
        run: cd client && npm ci
      - name: Install Server Dependencies 📦
        run: cd server && npm ci
      - name: Start Server
        run: |
          cd server
          npm start & npx wait-on --time-out 60000
      - name: Create React Build 🏗️ & Run Cypress Tests 🧪
        uses: cypress-io/github-action@v3
        with:
          project: project-2/client
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
